compressors:
  - name: "ahmad"
    power: 0.479
    latency: 5.361
    area: 0.01
  - name: "akbari"
    power: 0.759
    latency: 5.353
    area: 0.008
  - name: "ACFGII_1"
    power: 0.503
    latency: 4.408
    area: 0.0